### ISSUE TITLE
Don't show 'searching for NAME...' with -m

### ISSUE THREAD

**Issue by shtrom** [geier/pycarddav#112]
Or, alternatively, output it to stdout (e.g., stderr), but better if no displayed.

Otherwise, mutt takes "searchingforNAME" as an entry found in the address book.

**Comment by geier** [comment]
How did you configure mutt (and which version are you running?) I actually put that line in because mutt always swallowed the first...

I'm asking because if I just configured mutt wrongly, the better solution would be to remove that line.

**Comment by shtrom** [comment]
On Fri, Feb 13, 2015 at 03:58:35AM -0800, Christian Geier wrote:
> How did you configure mutt (and which version are you running?) I actually put that line in because mutt always swallowed the first...
> I'm asking because if I just configured mutt wrongly, the better solution would be to remove that line.

Ah!

   set query_command="lbdbq '%s'; pc_query -m '%s'"

lbdb *does* output an initial line which is, indeed, eaten by mutt.
However, running both in sequence, there is one too many info lines.

This is annoying, but this is specific to my config, so this PR is not
relevant.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by shtrom** [comment]
On Fri, Feb 13, 2015 at 11:33:23PM +1100, Olivier Mehani wrote:
> > How did you configure mutt (and which version are you running?) I actually put that line in because mutt always swallowed the first...
> > I'm asking because if I just configured mutt wrongly, the better solution would be to remove that line.
> Ah!
> 
>    set query_command="lbdbq '%s'; pc_query -m '%s'"
> 
> lbdb *does* output an initial line which is, indeed, eaten by mutt.
> However, running both in sequence, there is one too many info lines.

Well, here's a workaround:

    lbdbq 'thomas'; pc_query -m 'thomas' | sed 1d

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.
